import type { CuriosityBriefing } from './types';

const books = [
  { title: 'The Design of Everyday Things', author: 'Don Norman', description: 'A practical look at why some products feel obvious and others feel frustrating. It connects psychology, design, and the small decisions that make tools easier to use.', why: 'Useful for building calmer, more understandable websites and software.', url: 'https://jnd.org/books/the-design-of-everyday-things-revised-and-expanded/' },
  { title: 'The Information', author: 'James Gleick', description: 'A history of ideas about information, from language and code to the digital age. It shows how a scientific concept reshaped communication and computing.', why: 'A thoughtful bridge between science, teaching, writing, and technology.', url: 'https://www.jamesgleick.com/the-information/' },
  { title: 'Range', author: 'David Epstein', description: 'An exploration of why broad experience can be an advantage in a world that rewards specialization. The book uses research and stories rather than simple productivity slogans.', why: 'Relevant to a developer, teacher, and learner with several connected interests.', url: 'https://davidepstein.com/the-range/' },
];

const oneThings = [
  { title: 'Why does an LLM generate text one token at a time?', explanation: 'An LLM does not write a whole answer in one step. It converts the context into numbers, estimates a probability for the next token, selects one, then runs the expanded context through the model again. A token may be a word, part of a word, punctuation, or whitespace. This repeated prediction makes streaming possible and lets each new token depend on everything already written. It also explains why a model can sound coherent locally while still drifting globally: each choice is made from probabilities, not from a guaranteed outline of the finished answer.', url: 'https://developers.google.com/machine-learning/crash-course/llm/prompting' },
  { title: 'Why does a database index make a query faster?', explanation: 'A database index is an additional, organized lookup structure built beside a table. Without one, the database may inspect every row to find matching records. With one, it can navigate a smaller structure—often a B-tree—to locate likely row positions quickly. The trade-off is space and work on writes: every insert, update, or delete may also need to update the index. Indexes help most when they match real filters and sort orders; adding one to every column can make a system slower rather than faster.', url: 'https://www.postgresql.org/docs/current/indexes.html' },
  { title: 'Why can a fast server still produce poor Core Web Vitals?', explanation: 'Server response time is only one part of the journey to a usable page. A page can receive HTML quickly and still feel slow if it sends a large JavaScript bundle, waits for client rendering, shifts content when images load, or blocks the main thread with expensive work. Core Web Vitals measure what the visitor experiences: loading, visual stability, and interaction responsiveness. Improving them often means reducing browser work and reserving layout space, not only upgrading the server.', url: 'https://web.dev/articles/vitals' },
];

const lessons = [
  { topic: 'Bayesian reasoning as an update rule', explanation: 'Bayes’ theorem is a disciplined way to update a belief after seeing evidence. Start with a prior belief, measure how likely the evidence is under competing explanations, then normalize. It is less about complicated arithmetic than about making assumptions visible and revisable.', url: 'https://plato.stanford.edu/entries/bayes-theorem/' },
  { topic: 'The bicycle principle of gradient descent', explanation: 'Imagine standing on a foggy hillside and wanting to reach the lowest point. You can feel the slope beneath your feet, take a small step downhill, and repeat. Gradient descent does the same with a model: the gradient says which direction increases error, and a learning rate controls the step size.', url: 'https://developers.google.com/machine-learning/crash-course/linear-regression/gradient-descent' },
  { topic: 'Why web browsers use the event loop', explanation: 'JavaScript can run one piece of code at a time, but a browser still needs to wait for network and timer work without freezing the page. The event loop places completed callbacks in a queue and runs them when the current stack is clear, keeping the interface responsive while I/O is pending.', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Execution_model' },
];

export function dailyEditorial(date: string): Pick<CuriosityBriefing, 'book' | 'oneThing' | 'learning'> {
  const day = Math.floor(Date.parse(`${date}T00:00:00Z`) / 86_400_000);
  return { book: books[day % books.length], oneThing: oneThings[day % oneThings.length], learning: lessons[day % lessons.length] };
}
